### ISSUE TITLE
Wavedash Fullhop jump count shows 5f when holding down the button

### ISSUE THREAD

**Issue by cbartsch** [AlexanderHarrison/TrainingMode-CommunityEdition#149]
The new wavedash overlay shows that the button was held for 5 frames when you keep holding it during the wavedash. (The actual number it shows seems to be `(jumpsquat frames) + 1`)

I am slow with releasing I release the jump button, it usually shows 5f or something between 7-10 when I release it "quicker".

![image](https://github.com/user-attachments/assets/e1c6ac21-6cd3-4f1f-b4e3-4e9d11105d62)

(still an amazing feature, thanks for adding it!)

EDIT: It also seems to show (kinda funnily) wrong data for wavelanding:

![image](https://github.com/user-attachments/assets/1c104ada-01e2-48f1-8d67-07f89f713b06)

**Comment by AlexanderHarrison** [comment]
We check how many frames jump has been held exactly when the character reaches the ground from an airdodge. Because of how OSDs are programmed, this is difficult to change. It would be nice to post-process the OSD to increment the jump held frames when the player keeps holding jump down during the wavedash, but I don't think this is necessary.

The large invalid frame count is a debug value that occurs when you airdodge into the ground either later than 32 frames from the initial jump, or when the player does some other action in between the jump and airdodge (commonly a double jump). I've fixed this (just by not showing the invalid bottom line) in 058d0ca. 

Thanks for the great issue!

**Comment by cbartsch** [comment]
Thanks for the fix!

**Comment by cbartsch** [comment]
> We check how many frames jump has been held exactly when the character reaches the ground from an airdodge. Because of how OSDs are programmed, this is difficult to change

I guess you could just show "(held)" if the button is currently still pressed when landing with the airdodge?

> The large invalid jump frame count is a debug value that occurs when you airdodge into the ground either later than 32 frames from the initial jump

For the record, the wavedash frame was working properly for wavelands as well with vanilla Uncle Punch.

![image](https://github.com/user-attachments/assets/0778f170-e086-4d87-9d1a-0734e1773b5e)

**Comment by cbartsch** [comment]
@AlexanderHarrison
